version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    resource_class: small

    steps:
      - checkout
      - run: npm i
      - run: npm run test

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
