version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout
      - run: npm i
      - run: npm run test

  arch-check:
    docker:
      - image: archlinux/base:latest

    steps:
      - run: w

  deploy:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: w

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - arch-check
      - deploy:
          requires:
            - test
