version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout
      - run: npm i
      - run: npm run test

  arch-check:
    docker:
      - image: archlinux/base:latest

    steps:
      - run: env

  deploy:
    docker:
      - image: circleci/python:latest

    steps:
      - run: env

  remote-docker-check:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - run: env
      - setup_remote_docker
      - run: env
      - run: docker run archlinux/base env

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - arch-check
      - remote-docker-check
      - deploy:
          requires:
            - test
